### ISSUE TITLE
.env?

### ISSUE THREAD

**Issue by claudiorrrr** [docs-plus/docs.plus#140]
the documentation is not clear about the contents of the .env file required for development environment. 

I tried with the docker-compose file, but 

```40.33 unhandledRejection Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
40.33     at createClientComponentClient (/app/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:47:11)
40.33     at 1635 (/app/packages/webapp/.next/server/chunks/896.js:1:25265)
40.33     at o (/app/packages/webapp/.next/server/webpack-runtime.js:1:127)
40.33     at 7540 (/app/packages/webapp/.next/server/chunks/896.js:1:103)
40.33     at o (/app/packages/webapp/.next/server/webpack-runtime.js:1:127)
40.33     at /app/packages/webapp/.next/server/chunks/896.js:1:923
40.33     at o.a (/app/packages/webapp/.next/server/webpack-runtime.js:1:866)
40.33     at 9069 (/app/packages/webapp/.next/server/chunks/896.js:1:671)
40.33     at o (/app/packages/webapp/.next/server/webpack-runtime.js:1:127)
40.33     at /app/packages/webapp/.next/server/chunks/896.js:1:11878 {
40.33   type: 'Error'
40.33 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm assuming this is also because of that, although there no mention to any `NEXT_PUBLIC_SUPABASE_ANON_KEY` in the documentation. 

A dummy .env file will be quite useful!

**Comment by HMarzban** [comment]
Thanks for bringing this up! 
We’re in the middle of development, and the `README` hadn’t been updated for a while. 
Good news I just refreshed it with instructions on setting up the `.env` files and configuring Supabase. 🚀 😊

You’ll now find everything you need to get docs.plus running smoothly in the updated `README`.

If you run into any more issues or more info, feel free to reach out! ☘️

Thanks! 🙌

**Comment by claudiorrrr** [comment]
Brilliant. it's great to know you are in the middle of dev. Any chance to look at your plans on that?

I will add up more issues while I'm finding ways to improve the self hosted version (I'm guessing that's the easiest way for you to keep track of it)
