### ISSUE TITLE
[editor]: toggle animation can be improved

### ISSUE THREAD

**Issue by HMarzban** [docs-plus/docs.plus#26]

**Comment by edsaperia** [comment]
The crinkle should collapse and expand during the folding and unfolding animations. This makes it easier for the users to see what has been hidden or revealed. You have already animated this motion in the hover state, this should be very similar.

Here is a sketch for folding. Unfolding will be the same but in reverse.
![folding animation sketch](https://user-images.githubusercontent.com/5703915/214021826-541c47c5-b8cd-4f05-b8e5-d64ccd4a2bcd.png)
