### ISSUE TITLE
[editor]:  toggle icons ▶ 🔽 should be vertically centred on headings

### ISSUE THREAD

**Issue by HMarzban** [docs-plus/docs.plus#27]

**Comment by edsaperia** [comment]
At the moment, toggle icons are aligned with the top of the heading area:

![image](https://user-images.githubusercontent.com/5703915/214023194-bd936817-ea2f-453b-89e1-0f05795a5db3.png)

This is confusing, especially if there are many headings close together.

Instead, they should be aligned with the vertical centre of the headings.

**Comment by HMarzban** [comment]
This part has been refactored. It works great. I should consider writing a schema checker for the heading block later to prevent users from inserting unordered schema.
