### ISSUE TITLE
Paste into a doc

### ISSUE THREAD

**Issue by amberrignell** [docs-plus/docs.plus#3]
* * *

name: Paste text
labels: enhancement
assignees: 

* * *

**Is your feature request related to a problem? Please describe.**
If I copy text from another page, I'm unable to paste it into the document 

**Additional context**

**Comment by HMarzban** [comment]
Oh, thanks for opening a new issue.
Would you give me more detail to replicate this situation? Or if you share the link, you were tested with.

**Comment by amberrignell** [comment]
I tested on demo, copy pasting within the document works but I copied a link from my browser and tried to paste it and it didn't work, whereas pasting into my notes app did.

**Comment by HMarzban** [comment]
Good, I'll check it.

**Comment by HMarzban** [comment]
This issue arises from time to time; I can not replicate this issue now!

The only clue I have is that when a new build happens, the priority of execution of the internal hooks will be changed, which raises this problem! 
________________________________

So to find more clues to resolve the issue, I'm going to deactivate those copy/paste functions that I know could cause this problem. 

Then I check each one separately and have to modify it again if needed.

Another way I can think of is to take all the copy and paste functions apart and isolate the process in a new and creative way!

________________________________
New update; we have two active plugins that can manipulate the copy/cut/paste functions:

1/ `ep_full_hyperlinks`
2/ `ep_insert_media`

Also, the `ep_comments_page` plugin that comes into play later has access to that functionality. We will have to consider this plugin later.

These issues arise from that two plugins!
