### ISSUE TITLE
Design a new modal box that accommodates the Table of contents and more.

### ISSUE THREAD

**Issue by HMarzban** [docs-plus/docs.plus#91]
A modal box that opens from the left side of the screen and contains the document title, filter button, and table of contents.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/20157508/231219108-6ed6133c-2d59-4dea-926b-02fab677bcef.png">

**Comment by HMarzban** [comment]
@edsaperia, I need your opinion about the arrow icons representing open and closed headings! Should I put them here too, or not?

**Comment by edsaperia** [comment]
Yes I think so!
