### ISSUE TITLE
crinkles no longer display

### ISSUE THREAD

**Issue by HMarzban** [docs-plus/docs.plus#95]
This problem mostly occurs in the first part of the documents. And I think it has to do with the Heading ID!

Start at https://stage.docs.plus/open/test/dog, open all the headings in the first section "Animal Handbook", then close all the headings starting from "Classification of Animal Types" upwards

https://files.slack.com/files-pri/T01EWPFLLS3-F053BMRBUTS/image.png

![image](https://user-images.githubusercontent.com/20157508/231236905-e60bb05d-38cb-4e4f-a512-cce6c531a7d9.png)

**Comment by edsaperia** [comment]
I confirm that I can replicate this issue.

**Comment by HMarzban** [comment]
@edsaperia I need your approval; Please test it again and let me know the result.
